### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by maeng-kim** [AND-SOPT-iOS/KimHyunSoo#8]
## ⚡️Issue
명세서 기반 앱 구현

## 🍀TO-DO

- [x] 로그인 시 토큰 관리 방식 채택
- [x] 유저 등록
- [x] 유저 로그인
- [x] 취미 조회
- [x] 타인 취미 조회
- [x] 유저 정보 업데이트
